version: '2.3'
services:
  rtmp:
    image: yukimochi/vrc_rtmp:latest
    restart: always
    ports:
      - "80:80"
      - "1935:1935"
    mem_limit: 1024M
    volumes:
     - "./static:/static"
     - "./logs:/var/log/nginx"
     - "./nginx.conf:/etc/nginx/nginx.conf"
